name: Deploy GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

# Установка разрешений, необходимых для деплоя на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Настройка GitHub Pages
        uses: actions/configure-pages@v4

      - name: Загрузка артефактов
        uses: actions/upload-pages-artifact@v3
        with:
          # Загружаем всю папку репозитория (включая index.html и manifest.json)
          path: '.'

      - name: Деплой на GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
